# Generated by cucumber-sinatra. (Fri Jun 11 23:34:14 -0400 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'quizzy.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Sinatra::Application.set(:environment, :test)

World do
  Capybara.app = Sinatra::Application
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

def cleanable_collections
  Mongoid.database.collections.reject { |c| c.name == "system.indexes" }
end

#hooks

Before do
  cleanable_collections.each(&:drop)
end


After do
  cleanable_collections.each(&:drop)
end
